#!/usr/bin/env python3
"""Writes X509/Data.lean: the real certificates in certs/ as Lean data the kernel can read.

Each certificate is one big hexadecimal numeral plus its length. Lean's kernel turns that into a list of bytes
with GMP arithmetic, which is far lighter than a list literal of a thousand numbers."""
import subprocess, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
certs = [
    ("leaf", "github.io.pem", "*.github.io, the certificate keithadler.github.io serves, issued by Let's Encrypt YR1"),
    ("yr1", "yr1.pem", "Let's Encrypt YR1, issued by ISRG Root YR"),
    ("rootYR", "root-yr.pem", "ISRG Root YR, cross-signed by ISRG Root X1"),
    ("isrgX1", "isrg-root-x1.pem", "ISRG Root X1, the trust anchor (self-signed)"),
]
out = ["/-! Generated by `scripts/embed.py` from the PEM files in `certs/`. Do not edit. -/", "",
       "namespace X509.Data", "",
       "/-- `k` big-endian bytes of `n`, most significant first. -/",
       "def bytesOf (n : Nat) : Nat → List Nat → List Nat",
       "  | 0, acc => acc",
       "  | k + 1, acc => bytesOf (n >>> 8) k ((n &&& 0xFF) :: acc)", ""]
for name, f, doc in certs:
    der = subprocess.run(["openssl", "x509", "-in", str(root / "certs" / f), "-outform", "der"],
                         capture_output=True, check=True).stdout
    h = der.hex()
    out.append(f"/-- {doc}: {len(der)} bytes of DER. -/")
    out.append(f"def {name}Hex : Nat := 0x{h}")
    out.append(f"def {name} : List Nat := bytesOf {name}Hex {len(der)} []")
    out.append("")
out.append("end X509.Data")
(root / "X509" / "Data.lean").write_text("\n".join(out) + "\n")
print("wrote X509/Data.lean")
